### ISSUE TITLE
🛠 Add intent rule file of `capitalized-comments`

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#104]
## Overview

* Add intent error file of `capitalized-comments`

* See https://eslint.org/docs/latest/rules/capitalized-comments

## Default

```
  capitalized-comments:
    - error
    - always
    - ignoreInlineComments: false
      ignoreConsecutiveComments: false
      ignorePattern: ^$
```

## Setting

```
  capitalized-comments:
    - off # error
    - always
    - ignoreInlineComments: false
      ignoreConsecutiveComments: false
      ignorePattern: ^$
```
