### ISSUE TITLE
🛠 Add intent rule file of `dot-notation`

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#120]
## Overview

* Add intent error file of `dot-notation`

* See https://eslint.org/docs/latest/rules/dot-notation

## Default

```
  dot-notation:
    - error
    - allowKeywords: true
      allowPattern: ^$
```

## Setting

```
  dot-notation:
    - off # error
    - allowKeywords: true
      allowPattern: ^$
```
