### ISSUE TITLE
🛠 Add intent rule file of `no-bitwise`

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#130]
## Overview

* Add intent error file of `no-bitwise`

* See https://eslint.org/docs/latest/rules/no-bitwise

## Default

```
  no-bitwise:
    - error
    - allow: []
      int32Hint: false
```

## Setting

```
  no-bitwise:
    - off # error
    - allow: []
      int32Hint: false
```
