### ISSUE TITLE
🛠 Add intent rule file of `max-lines`

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#163]
## Overview

* Add intent error file of `max-lines`

* See https://eslint.org/docs/latest/rules/max-lines

## Default

```
  max-lines:
    - error
    - max: 300
      skipBlankLines: false
      skipComments: false
```

## Setting

```
  max-lines:
    - off # error
    - max: 300
      skipBlankLines: false
      skipComments: false
```
