### ISSUE TITLE
🛠 Add intent rule file of `max-lines-per-function`

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#165]
## Overview

* Add intent error file of `max-lines-per-function`

* See https://eslint.org/docs/latest/rules/max-lines-per-function

## Default

```
  max-lines-per-function:
    - error
    - max: 50
      skipBlankLines: false
      skipComments: false
      IIFEs: false
```

## Setting

```
  max-lines-per-function:
    - off # error
    - max: 50
      skipBlankLines: false
      skipComments: false
      IIFEs: false
```
