### ISSUE TITLE
🛠 Add intent rule file of `no-underscore-dangle`

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#174]
## Overview

* Add intent error file of `no-underscore-dangle`

* See https://eslint.org/docs/latest/rules/no-underscore-dangle

## Default

```
  no-underscore-dangle:
    - error
    - allow: []
      allowAfterThis: false
      allowAfterSuper: false
      allowAfterThisConstructor: false
      enforceInMethodNames: false
      enforceInClassFields: false
      allowFunctionParams: true
      # allowInArrayDestructuring: true
      # allowInObjectDestructuring: true
```

## Setting

```
  no-underscore-dangle:
    - off # error
    - allow: []
      allowAfterThis: false
      allowAfterSuper: false
      allowAfterThisConstructor: false
      enforceInMethodNames: false
      enforceInClassFields: false
      allowFunctionParams: true
      # allowInArrayDestructuring: true
      # allowInObjectDestructuring: true
```
