### ISSUE TITLE
⚙️ Add linted files for `jsdoc/require-file-overview`

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#373]
## Overview

* Add intent error file of `jsdoc/require-file-overview`

* See https://github.com/gajus/eslint-plugin-jsdoc/blob/main/docs/rules/require-file-overview.md

## Default

```
  jsdoc/require-file-overview:
    - error
    - tags:
        file:
          initialCommentsOnly: true
          mustExist: true
          preventDuplicates: true
```

## Setting

```
  jsdoc/require-file-overview:
    - off # error
    - tags:
        file:
          initialCommentsOnly: true
          mustExist: true
          preventDuplicates: true
```
