### ISSUE TITLE
⚙️ Add linted files for `jsdoc/text-escaping`

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#375]
## Overview

* Add intent error file of `jsdoc/text-escaping`

* See https://github.com/gajus/eslint-plugin-jsdoc/blob/main/docs/rules/text-escaping.md

## Default

```
  jsdoc/text-escaping:
    - error
    # Must include either `escapeHTML` or `escapeMarkdown` (or both).
    - escapeHTML: false
      escapeMarkdown: false
```

## Setting

```
  jsdoc/text-escaping:
    - off # error
    # Must include either `escapeHTML` or `escapeMarkdown` (or both).
    - escapeHTML: false
      escapeMarkdown: false
```
