### ISSUE TITLE
⚙️ Add linted files for `jsdoc/require-description`

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#377]
## Overview

* Add intent error file of `jsdoc/require-description`

* See https://github.com/gajus/eslint-plugin-jsdoc/blob/main/docs/rules/require-description.md

## Note

* SInce exists `jsdoc/no-blank-blocks`, so this rule is unnecessary.

## Default

```
  jsdoc/require-description:
    - error
    - checkConstructors: true
      checkGetters: true
      checkSetters: true
      # When use contexts, this rule will not work.
      # contexts: []
      descriptionStyle: body
      exemptedBy:
        - inheritdoc
```

## Setting

```
  jsdoc/require-description:
    # SInce exists `jsdoc/no-blank-blocks`, so this rule is unnecessary.
    - off # error
    - checkConstructors: true
      checkGetters: true
      checkSetters: true
      # When use contexts, this rule will not work.
      # contexts: []
      descriptionStyle: body
      exemptedBy:
        - inheritdoc
```
