### ISSUE TITLE
⚙️ Add linted files for `jsdoc/require-example`

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#383]
## Overview

* Add intent error file of `jsdoc/require-example`

* See https://github.com/gajus/eslint-plugin-jsdoc/blob/main/docs/rules/require-example.md

## Default

```
  jsdoc/require-example:
    - error
    - checkConstructors: true
      checkGetters: false
      checkSetters: false
      # contexts: []
      enableFixer: true
      exemptedBy:
        - inheritdoc
      exemptNoArguments: false
```

## Setting

```
  jsdoc/require-example:
    - off # error
    - checkConstructors: true
      checkGetters: false
      checkSetters: false
      # contexts: []
      enableFixer: true
      exemptedBy:
        - inheritdoc
      exemptNoArguments: false
```
