### ISSUE TITLE
⚙️ Add linted files for `jsdoc/require-description-complete-sentence`

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#389]
## Overview

* Add intent error file of `jsdoc/require-description-complete-sentence`

* See https://github.com/gajus/eslint-plugin-jsdoc/blob/main/docs/rules/require-description-complete-sentence.md

## Note

* Turn off `jsdoc/require-description-complete-sentence`, because default tags include, and force apply to `@params` and `@returns`.

## Default

```
  jsdoc/require-description-complete-sentence:
    - error
    - abbreviations: []
      newlineBeforeCapsAssumesBadSentenceEnd: false
      tags: []
```

## Setting

```
  jsdoc/require-description-complete-sentence:
    - off # error
    - abbreviations: []
      newlineBeforeCapsAssumesBadSentenceEnd: false
      tags: []
```
