### ISSUE TITLE
🛠 Add intent rule file of `line-comment-position`

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#62]
## Overview

* Add intent error file of `line-comment-position`

* See https://eslint.org/docs/latest/rules/line-comment-position

## Default

```
  line-comment-position:
    - error
    - position: above
      applyDefaultIgnorePatterns: true
      ignorePattern: ^$
```

## Setting

```
  dot-location:
    - off # error
    - position: above
      applyDefaultIgnorePatterns: true
      ignorePattern: ^$
```
