### ISSUE TITLE
🛠 Add intent rule file of `no-magic-numbers`

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#67]
## Overview

* Add intent error file of `no-magic-numbers`

* See https://eslint.org/docs/latest/rules/no-magic-numbers

## Default

```
  no-magic-numbers:
    - error
    - detectObjects: false
      enforceConst: false
      ignore: []
      ignoreArrayIndexes: false
      ignoreDefaultValues: false
      # ignoreClassFieldInitialValues: false
```

## Setting

```
  no-magic-numbers:
    - off # error
    - detectObjects: false
      enforceConst: false
      ignore: []
      ignoreArrayIndexes: false
      ignoreDefaultValues: false
      # ignoreClassFieldInitialValues: false
```

* テストで配列に id を列挙したい場合、其れを ignore する術がないので、以下の設定は放棄する。
```
  no-magic-numbers:
    - error
    - detectObjects: false
      enforceConst: true # false
      ignore:
        - -1
        - 0
        - 1
      ignoreArrayIndexes: true # false
      ignoreDefaultValues: true # false
      # ignoreClassFieldInitialValues: false
```
