### ISSUE TITLE
🛠 Add intent rule file of `no-extra-parens`

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#82]
## Overview

* Add intent error file of `no-extra-parens`

* See https://eslint.org/docs/latest/rules/no-extra-parens

## Default

```
  no-extra-parens:
    - error
    - all
    - conditionalAssign: false
      returnAssign: false
      nestedBinaryExpressions: false
      ignoreJSX: none
      enforceForArrowConditionals: false
      enforceForSequenceExpressions: false
      enforceForNewInMemberExpressions: false
      enforceForFunctionPrototypeMethods: false
      # allowParensAfterCommentPattern: RegExp
```

## Setting

```
  no-extra-parens:
    - off # error
    - all
    - conditionalAssign: false
      returnAssign: false
      nestedBinaryExpressions: false
      ignoreJSX: none
      enforceForArrowConditionals: false
      enforceForSequenceExpressions: false
      enforceForNewInMemberExpressions: false
      enforceForFunctionPrototypeMethods: false
      # allowParensAfterCommentPattern: RegExp
```

## Reason

```
/** @type {string} */
const ALPHA = /** @type {*} */ (Symbol()) // ❌ `(Symbol())` is extra parens by this rule
```
