### ISSUE TITLE
🛠 Add intent rule file of `max-len`

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#83]
## Overview

* Add intent error file of `max-len`

* See https://eslint.org/docs/latest/rules/max-len

## Default

```
  max-len:
    - error
    - code: 80
      tabWidth: 4
```

## Setting

```
  max-len:
    - off # error
    - code: 80
      tabWidth: 4
```
