### ISSUE TITLE
🛠 Add intent rule file of `sort-keys`

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#99]
## Overview

* Add intent error file of `sort-keys`

* See https://eslint.org/docs/latest/rules/sort-keys

## Default

```
  sort-keys:
    - error
    - asc
    - caseSensitive: true
      minKeys: 2
      natural: false
      allowLineSeparatedGroups: false
```

## Setting

```
  sort-keys:
    - off # error
    - asc
    - caseSensitive: true
      minKeys: 2
      natural: false
      allowLineSeparatedGroups: false
```
